# Removed obsolete 'version' tag

services:
  mixer-backend:
    # Use the image you built manually via SSH instead of building here
    image: mixer-backend-image:latest
    container_name: schedule1-mixer-backend # Optional: Give the container a specific name
    ports:
      # Maps port 3000 on your server (host) to port 3000 inside the container
      # If port 3000 is already used on your server, change the first number
      # (e.g., "3001:3000" would make it accessible via http://<server_ip>:3001)
      - "3000:3000"
    restart: unless-stopped # Automatically restart the container unless manually stopped
    networks:
      - mixer-network # Attach to a custom network (good practice)

networks:
  mixer-network: # Define the custom network
    driver: bridge

